#! /bin/bash
SCRIPTDIR="$( dirname -- "$BASH_SOURCE"; )";
apt update
apt install strongswan jool-tools python3-watchdog

# This is a very handy way. IPsec, when started in a namespace, will look for configs in 
# '/etc/netns/<namespace name>/ipsec.*' before it looks in '/etc/ipsec.*'.
cp -r $SCRIPTDIR/etc/* /etc/
cp -r $SCRIPTDIR/opt/* /opt/

/opt/ncubed/vpnc.service/install