[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vpnc"
description = "Manages ncubed-vpnc configuration"
readme = "README.md"
authors = [{ name="Tony Fortes Ramos", email="tony.fortesramos@ncubed.nl" }]
requires-python = ">=3.10"
keywords = ["ncubed", "vpnc", "vpn"]
license = {text = "GNU General Public License v3 (GPLv3)"}
# classifiers = [
#     "Framework :: Django",
#     "Programming Language :: Python :: 3",
# ]
dependencies = [
    "deepdiff==6.2.2",
    "Jinja2==3.1.2",
    "NetfilterQueue==1.0.0",
    "PyYAML==6.0",
    "scapy==2.5.0rc3",
    "typer[all]",
    "vici==5.9.3",
    "watchdog==2.2.0",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "bandit==1.7.4",
    "black==22.12.0",
    "mypy==0.991",
    "pylint==2.15.9",
]

[project.scripts]
vpnc = "vpnc.main:main"
vpnctl = "vpnc.ctl.main:app"
vpncmangle = "vpnc.mangle.main:main"

[tool.setuptools.dynamic]
version = {attr = "vpnc.__version__"}
