[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vpnc"
description = "Manages ncubed-vpnc configuration"
readme = "README.md"
authors = [{ name="Tony Fortes Ramos", email="tony.fortesramos@ncubed.nl" }]
requires-python = ">=3.10"
keywords = ["ncubed", "vpnc", "vpn"]
license = {text = "GNU General Public License v3 (GPLv3)"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
    "Operating System :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "deepdiff~=6.2",
    "Jinja2~=3.1",
    "NetfilterQueue~=1.1",
    "PyYAML~=6.0",
    "scapy~=2.5",
    "typer[all]",
    "vici~=5.9",
    "watchdog~=3.0",
    "pydantic~=2.4",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "bandit",
]

[project.scripts]
vpnc = "vpnc.main:main"
vpnctl = "vpnc.ctl.main:app"
vpncmangle = "vpnc.mangle.main:main"

[tool.setuptools.dynamic]
version = {attr = "vpnc.__version__"}
